### ISSUE TITLE
Parcel Error When Running in Firefox

### ISSUE THREAD

**Issue by willemneal** [jtenner/canvas-as#2]
I'm new to Parcel and after I cloned and built your project, when I build and run the test server I get:

```
TypeError: URL.createObjectURL is not a function[Learn More] demo-src.e31bb0bc.js:4780:11
parcelRequire<["index.js"]<
http://127.0.0.1:1234/demo-src.e31bb0bc.js:4780:11
newRequire
http://127.0.0.1:1234/demo-src.e31bb0bc.js:49:7
parcelRequire<
http://127.0.0.1:1234/demo-src.e31bb0bc.js:81:5
<anonymous>
http://127.0.0.1:1234/demo-src.e31bb0bc.js:10:18
```

I'll just stick to chrome for now, but just wanted to put this here.

**Comment by jtenner** [comment]
I don't know why that would be the case.

```ts
URL.createObjectURL()
```
This is a browser API documented here: https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL

Hope this helps!

**Comment by willemneal** [comment]
Yeah that’s the one I’m used to but it seems parcel is overwriting that definition.

**Comment by jtenner** [comment]
Heh. Parcel is a very unstable piece of software, since it has to be very opinionated. Thanks for the warning though.

Also, I'm not sure `canvas-as` has a future because I'm currently in the process of writing it's replacement along with a bunch of unit testing. In the meantime, I can try to be helpful if you hit any issues, however. Thanks for the feedback!

**Comment by willemneal** [comment]
Yeah I just wanted to play around with it because I’m looking for emulating a terminal in canvas.  I just found [this project](https://github.com/danikaze/ascii-ui), which seems to be exactly what I need.  How much work do you think it would be to translate this into canvas-as or your new endeavor?

**Comment by jtenner** [comment]
Well the goal of `canvas-as` is to help developers keep their code inside AssemblyScript, and I'm not an expert in how `ascii-ui` works. However, if you do manage to port the code to AssemblyScript, it would be very useful for sure!

As a philisophical note, it's hard to figure out the best way to render your example. Using the `canvas-as` api in this case might be slower than exporting a buffer that contains a bunch of view-state deltas. The question is this: "Is developer convenience more important than speed?"

It's a tough question to ask.

😓

**Comment by jtenner** [comment]
This repo is no longer maintained in favor of https://github.com/as2d/as2d .

**Comment by MaxGraey** [comment]
@jtenner Archive this repo in settings
